apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    tag: 41.0.2

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 2m
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: flux-system
  values:
    global:
      checkNewVersion: true
      sendAnonymousUsage: true

    deployment:
      kind: DaemonSet
      minReadySeconds: 2

    service:
      spec:
        ipFamilyPolicy: RequireDualStack

    api:
      dashboard: true
    ingressRoute:
      dashboard:
        enabled: true

    updateStrategy:
      type: RollingUpdate
      # rollingUpdate:
        # maxUnavailable: 1
    ingressClass:
      enabled: false

    gateway:
      name: traefik
      # defaultScope: "All"
      listeners:
        web:
          port: 8000
          hostname: "*.h3rmt.dev"
          protocol: HTTP
          namespacePolicy:
            from: All
        websecure:
          port: 8443
          hostname: "*.h3rmt.dev"
          protocol: HTTPS
          namespacePolicy:
            from: All
          mode: Terminate
          certificateRefs:
            - namespace: kube-system
              name: wildcard-h3rmt-dev-tls
        secure-mqtt:
          port: 8883
          # because some mqtt dont send sni header
          hostname: "*"
          protocol: TLS
          namespacePolicy:
            from: All
          allowedRoutes:
            kinds:
              - kind: TLSRoute
          mode: Terminate
          certificateRefs:
            - namespace: kube-system
              name: wildcard-h3rmt-dev-tls

    # Privacy-friendly Prometheus metrics (cluster-internal only)
    metrics:
      prometheus:
        # disable if deployed before prometheus
        enabled: false
        addRoutersLabels: true
        service:
          enabled: true
        # disable if deployed before prometheus
        serviceMonitor:
          enabled: false
      addInternals: false

    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false

    ports:
      web:
        port: 8000
        exposedPort: 80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
        observability:
          accessLogs: false
          metrics: false
          tracing: false
      websecure:
        port: 8443
        exposedPort: 443
        expose:
          default: true
        asDefault: true
        http3:
          enabled: true
          advertisedPort: 443
      secure-mqtt:
        port: 8883
        exposedPort: 8883
        expose:
          default: true
        observability:
          accessLogs: false
          metrics: false
          tracing: false
