# yaml-language-server: $schema=https://github.com/aclerici38/pocket-id-operator/releases/latest/download/pocketidoidcclient_v1alpha1.json

apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: flux
  namespace: flux-system
spec:
  description: "Flux (GitOps)"
  clientID: flux
  launchUrl: https://flux.h3rmt.dev
  callbackUrls:
    - "https://flux.h3rmt.dev/oauth2/callback"
  logoutCallbackUrls:
    - "https://flux.h3rmt.dev/"
  pkceEnabled: true
  allowedUserGroups:
    - name: flux-users
      namespace: pocket-id
  secret:
    enabled: true
    keys:
      clientSecret: CLIENT_SECRET
  clientSecretRotation:
    enabled: false
    interval: "720h" # rotate after 30 days
    window:
      opens: "0 3 * * *"  # cron (local TZ): 3am daily
      closesAfter: "3h"   