apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: << inputs.provider.name >>
        namespace: << inputs.provider.namespace >>
      spec:
        interval: 24h
        url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
        layerSelector:
          mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
          operation: copy
        ref:
          semver: "*"
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: << inputs.provider.name >>
        namespace: << inputs.provider.namespace >>
      spec:
        interval: 24h 
        releaseName: << inputs.provider.name >>
        serviceAccountName: << inputs.provider.name >>
        chartRef:
          kind: OCIRepository
          name: << inputs.provider.name >>
        values:
          web:
            enabled: true
            config:
              baseURL: https://flux.h3rmt.dev
              authentication:
                type: OAuth2
                oauth2:
                  provider: Pocket ID
                  clientID: flux
                  clientSecret: flux-oidc-credentials
                  issuerURL: https://auth.h3rmt.dev
            httpRoute:
              enabled: true
              annotations: 
                external-dns.kubernetes.io/ttl: "300"
              parentRefs: 
                - name: traefik
                  namespace: kube-system
                  kind: Gateway
                  sectionName: websecure
              hostnames:
                - flux.h3rmt.dev
          serviceMonitor:
            enabled: false