apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate
  namespace: renovate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renovate
      namespace: renovate
  template:
    metadata:
      labels:
        app: renovate
        namespace: renovate
    spec:
      containers:
        - name: renovate
          image: ghcr.io/renovatebot/renovate:44.145.3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: RENOVATE_CONFIG_FILE
              value: /etc/renovate/config.yaml
            - name: LOG_LEVEL
              value: info
            - name: RENOVATE_CONFIG_VALIDATION_ERROR
              value: "true"
            - name: RENOVATE_BASE_DIR
              value: /mnt/renovate-data
            - name: RENOVATE_CACHE_DIR
              value: /mnt/renovate-cache
          envFrom:
            - secretRef:
                name: renovate-secret-config
          volumeMounts:
            - name: renovate-config
              mountPath: /etc/renovate
              readOnly: true
            - name: renovate-data
              mountPath: /mnt/renovate-data
            - name: renovate-cache
              mountPath: /mnt/renovate-cache
      volumes:
        - name: renovate-config
          configMap:
            name: renovate-config
        - name: renovate-data
          persistentVolumeClaim:
            claimName: renovate-data
        - name: renovate-cache
          persistentVolumeClaim:
            claimName: renovate-cache
