apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-job
  namespace: renovate
spec:
  schedule: "0 */3 * * *" # Every 3 hours
  secretRef: renovate-secret-config
  provider:
    name: github
  image: ghcr.io/renovatebot/renovate:latest
  parallelism: 3
  discoveryFilters: 
    - "h3rmt/*"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - large
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook-token
        key: token
    sync:
      enabled: true
  renovateConfig:
    configMapRef: 
      name: renovate-config
      key: config.json5
  scratchVolume:
    enabled: true
    sizeLimit: "5Gi"
    
  extraEnv:
    - name: LOG_LEVEL
      value: "debug"
  githubAppReference:
    secretName: renovate-app-config
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
