apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-job
  namespace: renovate
spec:
  schedule: "0 * * * *" # Hourly
  secretRef: renovate-secret-config
  provider:
    name: github
  image: ghcr.io/renovatebot/renovate:latest@sha256:d21e806bd646e093c20a4bcdfa24598b687bd14e55079b1261404a81b1333cde
  parallelism: 3
  discoveryFilters: 
    # - "h3rmt/*"
    - "h3rmt/server-config"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - large
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook-token
        key: token
    sync:
      enabled: true
  renovateConfig:
    configMapRef: 
      name: renovate-config
      key: config.json5
  scratchVolume:
    enabled: true
    sizeLimit: "5Gi"
    
  extraEnv:
    - name: LOG_LEVEL
      value: "debug"
  githubAppReference:
    secretName: renovate-app-config
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
