apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-config.enc.yaml
  - secret-webhook.enc.yaml
  - operator
  - job.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
configMapGenerator:
  - name: renovate-config
    namespace: renovate
    files:
      - config.json5=config/config.json5
