# yaml-language-server: $schema=https://github.com/aclerici38/pocket-id-operator/releases/latest/download/pocketidoidcclient_v1alpha1.json

apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: renovate
  namespace: renovate
spec:
  description: "Renovate (Dependency Management)"
  clientID: renovate
  callbackUrls:
    - "https://renovate.h3rmt.dev/auth/callback"
  logoutCallbackUrls:
    - "https://renovate.h3rmt.dev/"
  pkceEnabled: true
  allowedUserGroups:
    - name: renovate-users
      namespace: pocket-id
  secret:
    enabled: true
    keys:
      clientSecret: CLIENT_SECRET
  clientSecretRotation:
    enabled: false
    interval: "720h" # rotate after 30 days
    window:
      opens: "0 3 * * *"  # cron (local TZ): 3am daily
      closesAfter: "3h"   