#!/usr/bin/env -S bash -c 'sops --encrypt "$0" > "${0/.raw.yaml/.enc.yaml}" && echo "Generated ${0/.raw.yaml/.enc.yaml}"'
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret-config
    namespace: renovate
stringData:
    GITHUB_COM_USER: ENC[AES256_GCM,data:uDQaiUI=,iv:180M4yocTA3JhfjtG6SWEtZp6jxzZm6qGIHc7fi9nsc=,tag:L/7rJnGMm9hP4xn/esu1lQ==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:xemJzsESSu+kQ4vgY8Ndz6IpKY27NVP2l3pkbJaTCRDurJBIOQZjvA==,iv:jQNAnLh7MwkGGm9YtwFKWgumnP6w5e3J5qS+iViMdww=,tag:PRiHmptHafVcL2leMv14gA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:8HcNezbISrXXeTewGZlHInK6IoJ1OUUmqKO2nCmNiTAM0+W4yLdGQQ34PqAJBEUoahq+l69i/ZWXBxVikKeF3oeRqbBou1I7cUh9SX3vRCyT8zaTqDojVHYiY3dV,iv:gWIwneJLXFIfwU8S5EcV+aB+XyfKF10TmkZDPgvRLh4=,tag:2VfveYIX18yFbHsLMrtQWA==,type:str]
    RENOVATE_GIT_PRIVATE_KEY: ENC[AES256_GCM,data:m2SzY/kJGXlz+A+5dOGfSU0d8Nueiyupgq97qAbkq7qE5msCN8jUPpRqX7keegkjMT8yGmaplEOG6JV6cg4jkDqg/5aGpGlIFc18krzBn+9Oc5ObaE6Yjra46msZoc2F6tdyeeB9msnR1jlQCni0XQi/QIGS9h5YSL4Zet8thKQqI+Cd36D/mCjb16R+ZurxhumBd9okkfoZm2v/fk+wpI26hl7Qhm8CO00YSwWvIRluqF+zLFebRaI+zd1CJ05wChx/XlhcHqmBeaYVcvLxlagKpSrJYQtVQpn8Pp0/vmS3709e2dfaNsVISW8J/gJz0q+gNonwVNJZjBmkBRWIDunjgon2lQa1+MUVqijuBgL9YgboMV8IOKUE9A/vecsKvHHVow7qs/gIC50KmraR4iotziV8Sblb/zUBQQ5l1perO44NSOOpQpSFdDu+WikVv4nPN1kjGmvbcDntSDO8cg1iSvHEKYb+XYQv7r4LRy6PQW6bn8UOASL1rJ9492S6NxjlJtBHuwKPPme1MtgmTXGYxZTmrQLWuJJ9ZI1NTFDY3NQEoR5P+oaFLuCvbPUGae+9dbsANTjgo32QHmukO0z/h5OjPiTndOyi9IPR90fS7IarYevBxH2gNgkyrGnhfOH1rg9t01TddPm6SoRdXc5fOjZjmChmEuCET70ZM0t4U3DBL/H0lsT5MF9HWDI4BXty3V8k5ulSOG1gUp7bLHky/sYvZ2ccLeuOGJ7YpaRI25LIqvB28C7JHU8kIuR2jvUqiFeKZ0VYR1HNj5Lb67dDtoKBGmd49nqy27cfgEj5obVL4GeYNWn4bArBStes2tFJOV+7z9bMp5TmQyxV7cyubiFUAO4h5VuKfDsu9gQbfaP0sHjSHy3pCq6gGBYEKYqdmD5OFSw1uUS93/VSkPPbmn24o+68k7aukp6WGxI0Dz2tEhxQz8QkArQ+B7erU6UbXPsvNsuxz4VMmjnJPzpScriM6v7eA92v,iv:QhWk5FB3FkEoReqD7zvO5KkSbZcF860bm2QpiCCxuDU=,tag:9Mxk/G4YjyHibNyrg35lyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVEdtSno4TzVDRUc1cGpM
            MjNtSUZocVVaandYRGRoMU8rNjkzSkcvQzNZCjcxLzMvYTlvcEVHMG1XV2k1ZDA1
            RVhYRWxTNGZyaDUwZmlhY0VXVHgwNXcKLS0tIGNpNmpCR2hicEhzUEdYY080V2Rw
            Tmt3OG0rVnAybm1wYWgwQjBKYlNWT0UKHoGSlH6sO8fqaYeygplRaAwhjvfVAa9x
            uI3N8WJLzJ7LqLEE039PdA5KLkEyZRcQDHRjxG6exJhzlC2weSK5Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:32:46Z"
    mac: ENC[AES256_GCM,data:RicKJW/YOK2cbxEbtWbAt195DY77hLy+rtJeeSyTa4CFSnucS6LiZoBpgA6jOn9NjoofsvRmoB0DiGWN1ymXdf+azRlV3g4EKURlLdzHKRRF8ZqEQlkEF3ZCL4KPYGfi7ne0VsRJshnRxYQ0be5eJ2XlIjnkjLy5Nws50Sw4nXI=,iv:vAgNKxvwszEjhI3TC850HpM4FLuntGeocejk/SMmUPY=,tag:1YTfLPegFdpvsMaBOLF2kA==,type:str]
    version: 3.13.3
