#!/usr/bin/env -S bash -c 'sops --encrypt "$0" > "${0/.raw.yaml/.enc.yaml}" && echo "Generated ${0/.raw.yaml/.enc.yaml}"'
apiVersion: v1
kind: Secret
metadata:
    name: renovate-webhook-token
    namespace: renovate
    metadata:
        labels:
            renovate-operator.mogenius.com/allow-ref: "true"
stringData:
    token: ENC[AES256_GCM,data:zA==,iv:sgu7YoIMwPH0g5LTLOGj9Fc5h2PXx9m6QhBjjrj7vU8=,tag:Ju36yancSU37EMbq3H2yMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbmU4RnJUdWJJRnJpVEU2
            bjJJTGsvK1p6UC9iMGlYTFJtTHRwMG9WVzFJCjFOaFVwWmM5Qk54ZnUrUjlWZC93
            Wkd0dkxiOTU0MTVKdjg4U25xTmxpV00KLS0tIGdYc0R1WXE4NnRhcTE5SVpRNXRN
            dTZBQ3YxbmxVS3grNXhFSUhXS1paRlEKtB2AnMATpQ8MzcLUbRWWCsnlZB6RPDc8
            Ytz7chcUgdJf7dcoYY8VQCxHU4FJVcugIg391Ker17BnO1/Cer1IgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:32:49Z"
    mac: ENC[AES256_GCM,data:1Vi3gYLWGPkV61vHAvBD+IBq+G9gF6yfmY+PL6blWtWxdsJkgaup9gJnuW2fkFvXEIhLNmsVNSjZ2+WAjNta1zUI617GdKiXhZa6mw7eeeD/LLsbdfnP4xEOZk4qTrD55zeVQ6/t+Sll+yvUpWvfRcGHm4KhPD2JSb4OL7Cw5Gk=,iv:eV7B8h3MyKN7LBQ5rXgtojzv1yhkJq7FmygbN233wV8=,tag:mgMVYTTFR0PlBZdKlONguw==,type:str]
    version: 3.13.3
