#!/usr/bin/env -S bash -c 'sops --encrypt "$0" > "${0/.raw.yaml/.enc.yaml}" && echo "Generated ${0/.raw.yaml/.enc.yaml}"'
apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret-config
    namespace: renovate
stringData:
    GITHUB_COM_USER: ENC[AES256_GCM,data:isMT6zs=,iv:VoICsW1MHiX1VSGtJm56c6GBS3GX4i4DI48J4tQJ8hk=,tag:U/gtTMl87YgoGbChu/ePjg==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:rTohRQuE6KUweJfDqOTy+EJpcv28buoow/dh9MOX+lN6hzWZUhY/ag==,iv:VItoMYGRLq0oeHGhp0O3bQH0KNbLOJq9JL0mFp/T40E=,tag:cJmgfWLirDb9ZvzMcY5ZZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc2s5cFFlRFhTaWV1NXpB
            UCt5ZGN6S0luTGZxRDZFLzd0YVpiYkNmNFgwCmJTS0JEMW05TEdYNjB5bk9Lc1F2
            Q25XNDJqZ3kzK0FUOEVidFdhaSsxOWcKLS0tIFdUd08zZzBpT2V3V2JSMUo2YlBW
            cXg4VmpXUVBmYUdvTWxKR3oxbm1xS1kKnjivXHRoDu13gqHzba/IJa72Dy+Upw3U
            kxv70luIV/Y7d2XbXar01c624REIMxKgoxRHKTubbsznJYWcSTR6eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:49:14Z"
    mac: ENC[AES256_GCM,data:iQ/Ho3BvElJ89zRJfi6VHuCIjm7gyexRv5wIdkb9YztaTmBCS3H3tTof/8Nsykz8Qe0Yyu5NxQwNq4rtMpptEjpF3BOAfAKp8eHKEjoqQu/PoichsWCxvG77qqAe3/tZEVnK7fZpdgICmYDqicdn8lX1685h4v/R/OuoahVoA0I=,iv:S7oJOqQOGCplJsRQsDcJob6XQEEXGafE6SLwnMyeu5M=,tag:zXjR0WK5ayyptlL5NjS3Yw==,type:str]
    version: 3.13.3
