#!/usr/bin/env -S bash -c 'sops --encrypt "$0" > "${0/.raw.yaml/.enc.yaml}" && echo "Generated ${0/.raw.yaml/.enc.yaml}"'
apiVersion: v1
kind: Secret
metadata:
    name: renovate-webhook-token
    namespace: renovate
    metadata:
        labels:
            renovate-operator.mogenius.com/allow-ref: "true"
stringData:
    token: ENC[AES256_GCM,data:mNMto48mki0qU89eLLZ2UVC+3LIgA3hQa/YJRF9n/F2aIumTlZjq5Z7zNEk=,iv:uZ9aPk9exqPCAQVxk30iPrd0c31sZV+MyNmBkGWPSOs=,tag:cgonT/IN9E1w3H1Nj4ehcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS1hFK1d3SkRsdDlEY1ln
            YldOZG9vME93bUhvNkRGTXVvcXBtQjNHY1RjClBybFljYlA2ZGNoRk41UU1QQkpT
            VEt6amVqanNubWNYK2lLZjJZblF1VlkKLS0tIEZMYjJ5T0c2WnJjenQ4M0NpTmR0
            dU1iTENtdytBcGxEOVVZK2k4QlY4VVkKGFjh+CdZJWNrqS9lwdZFN1LrIycNc5hx
            ZDKSmB8VykljxAkttKHPAMpBvZ7A08WrWEmsaKXesuAl2FLsJsI73g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T23:28:51Z"
    mac: ENC[AES256_GCM,data:YlnxDQePdWYslDCv0G4VIlAjXJdl65XBjLGXVu6xDVBhL/zpAIIyLcUOwqxbli1gFzVV++XrO15nMI0PYZ4WRlSbiDLb8hVC2GMxuh+WQoUNmRdOz4gfWV5/GqAcp24SyCLjt9EkKhhpbrP6qIO2u+W6AqOeYG4mwEsuRTutzRs=,iv:NbPwaYr4SqAWXQW6X2BQYbKKwSssqKM+hcs6lng7FLA=,tag:vINac6pYkyu+X04GkAHi2w==,type:str]
    version: 3.13.3
