apiVersion: v1
kind: Secret
metadata:
    name: admin-user-info
    namespace: pocket-id
stringData:
    username: ENC[AES256_GCM,data:QE7zp1td,iv:7ASSqmF2rrRETdUGDdc0gyKP/I6TvFsQy9kuySTJL1U=,tag:pKT+KfDo+kp++L8v2c5u6w==,type:str]
    firstName: ENC[AES256_GCM,data:q/gPlNTN,iv:8o5RTbSWabHgNS7lihHxKZd7G6FPiLTO2t8h1rK/hcY=,tag:dB2Nm4m+ZPdJATYlIINg2w==,type:str]
    lastName: ENC[AES256_GCM,data:YpOSEUGQTQ==,iv:45acJkJCalHTqLxUbf97VEAp9bHwgM8BMsy+u/1aaMQ=,tag:TneXJBRf0WQ3rSndvPpy5A==,type:str]
    email: ENC[AES256_GCM,data:8oVSVEXwDB2D8Iss84f/og==,iv:Q8rPET1/y55D0MNWlyppe71P6F9B19otR+p3qXHqsIU=,tag:OFygK1xyifEpWvpCS78H1A==,type:str]
    displayName: ENC[AES256_GCM,data:Ry0lQLqv,iv:j5lA/jvKmJWIj560BKw0qppHOx5YzxV6lS8oP8tRo/Q=,tag:eCAHahL+kipX0mQ8v3d8Rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Q3R2VFBPdXF0aG1LaEVB
            bFRncmJGU0ZZL3FKWGJ3YW51aEpEeWdFaVFRCi9UcUZDVy9MYldIb0xLYXpVR3RK
            MEo5QkVZQ2o5WC96R3JtcVhFelFYTjQKLS0tIFA5NTk5SzBINXVxOFFrK3VURHo2
            YTRRSkVUTHVPdUZWUmRyd2lVR1FOZk0KqRlsAs8xpZEcx2yNMSFO2bI6WKi8wNJ5
            xYQQCwPjT4XPCB/OuHRhzxKpcsIXYiTs6QETqY4bzULOacUY3vHP/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T18:20:18Z"
    mac: ENC[AES256_GCM,data:aAmVha5m2nCM6zsOeiWDJAF3sThNw4WsorvM/2IV6f/q7jaiG36fTJINvBqBodUoHPjD0aUk72wP9S6Jeu0gq4BBFcjQYwO37tjEUxa2uSImiHhg0f6TNpJ9bg4CIf+Y04yjQeIHwiDgBi6fKzutd7U4OBBo8lEdZRkC6VCPg8o=,iv:iUzeLDWUtsSwZ3QdQ8w2EiGMuoETCBeMGb2ZRImVeaM=,tag:nGrnA+GR10aOfehMVSLjjA==,type:str]
    version: 3.13.3
