apiVersion: v1
kind: Secret
metadata:
    name: enrico-user-info
    namespace: pocket-id
stringData:
    username: ENC[AES256_GCM,data:WWSCUm63,iv:wR+a6kaMgKJpafDFVTsTT2owoLsMTU7H8qoBJy6p6+Q=,tag:cQXisP+TSYsmibeiIK8LPg==,type:str]
    firstName: ENC[AES256_GCM,data:KV69SU10,iv:krfv+IP3o7cFvfl9FodLIiH0QsIHaZFdLjsABLXBgfw=,tag:k49iOM9001JvoQQ5GwxYWw==,type:str]
    lastName: ENC[AES256_GCM,data:v0cYFMWKxw==,iv:HJw9fqWT5JKlHEHEeuYWKfYRtToRHjav/IPwqJzQvlk=,tag:U67uJRQbE4tg/J41tXiUzA==,type:str]
    email: ENC[AES256_GCM,data:DMEE+vnp4obhj2s8nwM3/Q==,iv:FLYJ+SPFPFQamcg49C3LpheBAdN6UliL7WSskIxkTfY=,tag:8Of44DUFdqxrITKHW5e3kA==,type:str]
    displayName: ENC[AES256_GCM,data:dEKhOjjp,iv:4YxmIQ5CAFDAXse1vhyw2EuwcFQCXNdqII0TwNi7Jd0=,tag:4rSaikjMYvseMuFfA5CnZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWGtnalpwcjVjUWUrT1pI
            QUg4Y2p0MmdWNlk0NzhWWWlxajY0QjkvMms4Cm12ZUt6L2Q4OEI4YmhRVXpSM1Fh
            QXhDdTFTbE5SRVBqQ21qKzdBcUdZMzQKLS0tIGEzeDZQTTZacFd3RmVZaVZpeHZT
            bzdiUnVsTEM2ZEhWWHR4MllUY1dxc0UKG7t/SWh3+rG7ARlPeGx2gur3f64AiJqc
            K2zUAncX7PdfDUXA8Wy0qX0pr63WwnLeot4q+ZKqiM1J9Bkr3ZtQ4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T18:26:50Z"
    mac: ENC[AES256_GCM,data:hYYCzjFZ86PYDcv3+rTn5zB8U027Vbw2vTodDQzP2+BKlTtTE3UgvF51L0svDD+z2dmo5kQOdhoaYSWJ9R7fi0LETeH7+2WytHa6fXE0TE4syTfjeq/1tyD3oBH9ERCwhwRA8GLsiqWM1dScqjctR+WRTDPgdHgCIlDMKKVt4Sk=,iv:Xkv0AEaTxWucvlauVXYoJKkD5OICyUf2xqmpQVekgz4=,tag:2Qyxm5/Yg+UZ2V8mLAqn0Q==,type:str]
    version: 3.13.3
