apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oidc.yaml
  - operator.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
configMapGenerator:
  - name: renovate-operator-values
    namespace: renovate
    files:
      - values.yaml=renovate-operator-values.yaml
