# yaml-language-server: $schema=https://raw.githubusercontent.com/mogenius/renovate-operator/refs/heads/main/charts/renovate-operator/values.schema.json

webhook:
  baseUrl: https://renovate.h3rmt.dev
  baseUrlScheme: https

route:
  enabled: true
  annotations: 
    external-dns.kubernetes.io/ttl: "300"
  parentRefs: 
    - name: traefik
      namespace: kube-system
      kind: Gateway
      sectionName: websecure
  hostnames:
    - renovate.h3rmt.dev

auth:
  oidc:
    enabled: true
    clientId: renovate
    existingSecret: renovate-oidc-credentials
    secretKey: CLIENT_SECRET
    issuerUrl: https://auth.h3rmt.dev
    pkceEnabled: true
    redirectScheme: https

authorization:
  enabled: false

extraEnv:
  - name: TZ
    value: "Europe/Berlin"
