apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thread-matter
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thread-matter
  template:
    metadata:
      labels:
        app: thread-matter
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        thread-usb: "1"
      containers:
        - name: openthread-border-router
          image: ghcr.io/ownbee/hass-otbr-docker:7e60d50
          securityContext:
            privileged: true
          volumeMounts:
            - name: otbr-data
              mountPath: /data
          env:
            - name: DEVICE
              value: "/dev/ttyUSB0"
            - name: BACKBONE_IF
              value: "eth0"
            - name: NAT64
              value: "1"
            - name: OTBR_WEB_PORT
              value: "8085"
            - name: OTBR_WEB
              value: "1"
            - name: THREAD_BETA
              value: "0"
            - name: AUTOFLASH_FIRMWARE
              value: "0"
            - name: FLOW_CONTROL
              value: "0"
            - name: BAUDRATE
              value: "460800"
            - name: OTBR_LOG_LEVEL
              value: "notice"
        - name: matter
          image: ghcr.io/matter-js/matterjs-server:1.2.8
          volumeMounts:
            - name: matter-data
              mountPath: /data
          env:
            - name: PRODUCTION_MODE
              value: "1"
            - name: PRIMARY_INTERFACE
              value: "eth0"
      volumes:
        - name: otbr-data
          persistentVolumeClaim:
            claimName: otbr-data
        - name: matter-data
          persistentVolumeClaim:
            claimName: matter-data
