apiVersion: apps/v1
kind: Deployment
metadata:
  name: thread-matter
  namespace: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: thread-matter
  template:
    metadata:
      labels:
        app: thread-matter
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        thread-usb: "1"
        location: "home"
      containers:
        - name: openthread-border-router
          image: ghcr.io/ownbee/hass-otbr-docker:7e60d50@sha256:7be32cca581c239536527628169a4691ecc8d8e9dd6e95c5c40fb6cf3494128f
          securityContext:
            privileged: true
          volumeMounts:
            - name: otbr-data
              mountPath: /data
          env:
            - name: DEVICE
              value: "/dev/ttyUSB0"
            - name: BACKBONE_IF
              value: "eth0"
            - name: NAT64
              value: "1"
            - name: OTBR_WEB_PORT
              value: "8085"
            - name: OTBR_WEB
              value: "1"
            - name: THREAD_BETA
              value: "0"
            - name: AUTOFLASH_FIRMWARE
              value: "0"
            - name: FLOW_CONTROL
              value: "0"
            - name: BAUDRATE
              value: "460800"
            - name: OTBR_LOG_LEVEL
              value: "notice"
        - name: matter
          image: ghcr.io/matter-js/matterjs-server:1.4.0@sha256:54232d0d3e7dff5a54759469d2753399270412b4c30c55b31750a4595e4cb236
          volumeMounts:
            - name: matter-data
              mountPath: /data
          env:
            - name: PRODUCTION_MODE
              value: "1"
            - name: PRIMARY_INTERFACE
              value: "eth0"
      volumes:
        - name: otbr-data
          persistentVolumeClaim:
            claimName: otbr-data-longhorn
        - name: matter-data
          persistentVolumeClaim:
            claimName: matter-data-longhorn
