apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otbr-data-longhorn
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-data-longhorn
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
