apiVersion: v1
kind: Service
metadata:
  name: thread-matter-svc
  namespace: home-assistant
spec:
  selector:
    app: thread-matter
  ports:
    - name: otbr-rest
      port: 8081
      targetPort: 8081
    - name: otbr-web
      port: 8085
      targetPort: 8085
    - name: matter
      port: 5580
      targetPort: 5580
    - name: matter-com
      port: 5540
      targetPort: 5540