apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: faster-whisper
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faster-whisper
  template:
    metadata:
      labels:
        app: faster-whisper
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        "nvidia.com/gpu.present": "true"
        location: "home"
      containers:
        - name: faster-whisper
          image: lscr.io/linuxserver/faster-whisper:gpu-legacy
          ports:
            - name: faster-whisper
              containerPort: 10300
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Berlin

            # nvidia specific
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          command:
            - /bin/bash
            - "-c"
          args:
            - |
              export LD_LIBRARY_PATH="/lsiopy/lib/python3.14/site-packages/nvidia/cublas/lib:/lsiopy/lib/python3.14/site-packages/nvidia/cudnn/lib:${LD_LIBRARY_PATH}"
              exec s6-setuidgid abc python3 -m wyoming_faster_whisper \
                --uri tcp://0.0.0.0:10300 \
                --device cuda \
                --model small-int8 \
                --compute-type int8_float32 \
                --beam-size 1 \
                --language de \
                --data-dir /config \
                --download-dir /config
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: faster-whisper-config
