apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faster-whisper-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
