---
# Source: garage/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage
  namespace: garage

---
# Source: garage/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: garage
data:
  garage.toml: |-
    metadata_dir = "/mnt/meta"
    data_dir = "/mnt/data"

    db_engine = "lmdb"

    block_size = "1048576"

    replication_factor = 3
    consistency_mode = "consistent"

    compression_level = 1

    rpc_bind_addr = "[::]:3901"
    # rpc_secret will be populated by the init container from a k8s secret object
    rpc_secret = "__RPC_SECRET_REPLACE__"

    bootstrap_peers = [ 
    ]
  
    [kubernetes_discovery]
    namespace = "garage"
    service_name = "garage"
    skip_crd = false

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"

    [s3_web]
    bind_addr = "[::]:3902"
    index = "index.html"

    [admin]
    api_bind_addr = "[::]:3903"
    admin_token = "__ADMIN_TOKEN_REPLACE__"
---
# Source: garage/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-crds-garage-garage
  namespace: garage
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: ["deuxfleurs.fr"]
  resources: ["garagenodes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Source: garage/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-crds-for-garage-garage
  namespace: garage
subjects:
- kind: ServiceAccount
  name: garage
  namespace: garage
roleRef:
  kind: ClusterRole
  name: manage-crds-garage-garage
  apiGroup: rbac.authorization.k8s.io
---
# Source: garage/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: garage
  labels:
    name: garage
spec:
  type: ClusterIP
  ports:
    - port: 3900
      targetPort: 3900
      protocol: TCP
      name: s3-api
    - port: 3902
      targetPort: 3902
      protocol: TCP
      name: s3-web
    - port: 3903
      targetPort: 3903
      protocol: TCP
      name: admin
  selector:
    app: garage

---
# Source: garage/templates/workload.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: garage
  namespace: garage
spec:
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      serviceAccountName: garage
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        # Copies garage.toml from configmap to temporary etc volume and replaces RPC secret placeholder
        - name: garage-init
          image: "busybox:stable"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              sed -e "s/__RPC_SECRET_REPLACE__/$RPC_SECRET/" \
                  -e "s/__ADMIN_TOKEN_REPLACE__/$ADMIN_TOKEN/" \
                  /mnt/garage.toml > /mnt/etc/garage.toml
          env:
            - name: RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage-rpc-secret
                  key: rpcSecret
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: garage-webui-secret
                  key: apiAdminKey
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: configmap
              mountPath: /mnt/garage.toml
              subPath: garage.toml
            - name: etc
              mountPath: /mnt/etc
        - name: fix-permissions
          image: busybox:stable
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - chown -R 1000:1000 /mnt/meta /mnt/data
          securityContext:
            capabilities:
              add:
                - CHOWN
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            runAsUser: 0
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: meta
              mountPath: /mnt/meta
            - name: data
              mountPath: /mnt/data
      containers:
        - name: garage
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
          image: "dxflrs/amd64_garage:v2.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3900
              name: s3-api
            - containerPort: 3902
              name: web-api
            - containerPort: 3903
              name: admin
          volumeMounts:
            - name: meta
              mountPath: /mnt/meta
            - name: data
              mountPath: /mnt/data
            - name: etc
              mountPath: /etc/garage.toml
              subPath: garage.toml
          resources:
            {}
      volumes:
        - name: configmap
          configMap:
            name: garage-config
        - name: etc
          emptyDir: {}
        - name: meta
          hostPath:
            path: /var/lib/garage/meta
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /mnt/tank-garage
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: garage-webui
  namespace: garage
spec:
  type: ClusterIP
  ports:
    - port: 3909
      targetPort: 3909
      protocol: TCP
      name: webui
  selector:
    app: garage-webui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
  namespace: garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-webui
  template:
    metadata:
      labels:
        app: garage-webui
    spec:
      containers:
        - name: garage-webui
          image: khairul169/garage-webui:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3909
              name: webui
          env:
            - name: CONFIG_PATH
              value: /etc/garage.toml
            - name: API_BASE_URL
              value: http://garage:3903
            - name: API_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-webui-secret
                  key: apiAdminKey
            - name: AUTH_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: garage-webui-secret
                  key: authUserPass
            - name: S3_REGION
              value: garage
            - name: S3_ENDPOINT_URL
              value: http://garage:3900
          volumeMounts:
            - name: garage-config
              mountPath: /etc/garage.toml
              subPath: garage.toml
      volumes:
        - name: garage-config
          configMap:
            name: garage-config
