apiVersion: v1
kind: Service
metadata:
  name: home-assistant-svc
  namespace: home-assistant
spec:
  type: ClusterIP
  selector:
    app: home-assistant
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123