#!/usr/bin/env -S bash -c 'sops --encrypt "$0" > "${0/.raw.yaml/.enc.yaml}" && echo "Generated ${0/.raw.yaml/.enc.yaml}"'
apiVersion: v1
kind: Secret
metadata:
    name: pocket-id
    namespace: pocket-id
stringData:
    encryption_key: ENC[AES256_GCM,data:54m3nVgjGvqmh8sS0eWzjZyMN3DVhH9zD1bfNwAoloU8KeDULmVYot1wmcKX,iv:uu1NB52E0KCMt6xjkbKgWyQILZqfsfR8hVwUVZXxWhE=,tag:yNUHz9u0cg5R68rEQrOqyg==,type:str]
    smtp_password: ENC[AES256_GCM,data:OoTVxst7fLl2eh0Gt+lOrA==,iv:iYYlzkAUPVXAPy4dTO5Xy/zGRvt9B7pQc1f4g5YMOFM=,tag:fcBhVwjZVQ3H458nQd9+0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUUp2bkNlRnllM2czanhu
            L0JZLzA1OE5paytQaDEvVVo1bm9VS0hTY2hjCmFPbjc3QzM0QmM0bTEzRHFpV0Y1
            SzM5WHc0QmxXRHcrRU0vKzEwaWpWeWcKLS0tIGd3d0haQmtMYlhUdVNYNVFRSExK
            dHRHN29IR2N1UHBQbENzREtJSUEzY28K1st3vTNgwasJkdSY3siwP5BQeOaVRRmS
            P0DZyHc0UphYWmtybojHLcOoEFdTm5PMPZZyUpl6OH/8RAugvMRpfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:32:22Z"
    mac: ENC[AES256_GCM,data:7iPkFUpu/XmNPVQAF/uvctSBxQ42C/poc2Q6OH6AnlFpYWmwnsLjxWmMcHXpqUV8+uOWzH/8g71QcwovJDpb01YhR8M9ZX4fN6CHkvGrjA1GkS+LUdH7L7Zqd5oVzfNeh0USo/Rh9aZhQhGRpIABuRQwqlswk3Vcllpvbj+Pt30=,iv:seDNPoalbz9KA+NPqEJxdY7cwjRBbw7RJnaKJ3gQNG0=,tag:zbamidIWTsu9wRg2Dz09xA==,type:str]
    version: 3.13.3
