apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
    namespace: pocket-id
stringData:
    encryption_key: ENC[AES256_GCM,data:V+pA6xhJ094Y/uDYTD6Ha0Vu/Q8LWe2tllzySDWXxI51YSq59HvlT0LhmJsc,iv:IVzd6dyPnDgjEzh8+qbUVijxv7FaqEjlQi40tGg1VOc=,tag:v/hsFqbtYYJpk0qaLhRy6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbEtDUDg2eTlleW1ER3ZE
            NC9MNmtyc3FMSXVQZVB3ZjBscUxyemNCakZRCnpHczd2VllILy9CVWdVWGpuMjBj
            cWcwdHpMVEpHOGZ0NXlKbzFubzZDUnMKLS0tIGEreUYxc0NGdm1NWFlrTjBHZHFs
            U2l1alRiM0lGdEJOK0UrWkUwamQ5bVEKZbjFzNxZamTdz1bE3AEv5kUdk+6tvUuX
            4vaJDFS5vT8CxPhsxtdMt6tZm5f8L1YJDAlycurLkBbLZhtCIDtBZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T18:03:49Z"
    mac: ENC[AES256_GCM,data:MubMO9o7zDbnomvrKgXalHi0WrzgtylUbJbThp/ErWzsHe7XDyq9ilrINdl3Ix0Inr1/WEOt9Oxw2yLHo5AbasPC3ClUTGj1T28TSaDt7kDxzpTkeHCTQhIyvPTfAXZtaaRtA9JQ5br51FBzAOpfU0yXzsq8y9G4/bocrL0Z/LU=,iv:SFXUH2VbM2HlSsJAzMVtGPhVqA3dd+DF9kQo12khd/Y=,tag:5GSJSyvT160s3aZFr1sYpw==,type:str]
    version: 3.13.3
