apiVersion: v1
kind: Secret
metadata:
    name: pocket-id
    namespace: pocket-id
stringData:
    encryption_key: ENC[AES256_GCM,data:XVhmM8ajopX42COZ+KndMH8ibs/Yq08SkHxh79mzjYU6jlH6Mkr3jzYERj4S,iv:3qreyvaQytcfu/anpf7hQvclcy5Yj3EHweI6qBVqh3I=,tag:veBc99w/XRfBMZV0DxmN4g==,type:str]
    smtp_password: ENC[AES256_GCM,data:XZy2kkmAYnH2k3YkAktMzQ==,iv:WCVABb6MBKwSv37r6lBA6hlrerUaDkgDWwf5fFRbHo4=,tag:MdhYn9B98wjXvy/spEIGTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVXgvNzI0azF4WUMwM08z
            NTRkSlBaLzFHSzdRT3RYZUNFUGtTeGZ2MGxzCkxZSXJ2OTVSYUhqU1RRVVptK0RL
            a1ZHNEV0R0V0Yk0vdTB5WWd2OXJVclkKLS0tIG9sblR3UjVOZ1NyRHgxYU5OTi9l
            c3pMUWFFQWswaG9BY3lrdXFCalgwZXcKSUAr1Q5uNJFjxzDMBf5FVqJ3Djw+bWXn
            I6Tam3ibnd3FzfESeQzxfInNhl0tXLr04RQUXQmY2weENOnfDNvHGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T19:04:25Z"
    mac: ENC[AES256_GCM,data:nDLBl/m6h0Fhp8dS917ipesL5se6P1RgBRdQEhliLqt9JPSxJC00uCrHe5YETFt3ZWeiGnGi37lfeVTd4fMXBFUYkZFKdRgg13Ik30WqA5Enk7N+dgH4UuTL5U5vhCPW6mYSuPgdi9cta0RlqYQpiONj8IBiaZgz0KollYBzODE=,iv:qQ/ifJuwypfZAf9CdMrN7qSIVfAQPulazmH+YtZ+eYo=,tag:tiirSEyzs8xE41L1r3ND1Q==,type:str]
    version: 3.13.3
