apiVersion: v1
kind: Service
metadata:
  name: matter-server-svc
  namespace: home-assistant
spec:
  selector:
    app: matter-server
  ports:
    - name: matter
      port: 5580
      targetPort: 5580