apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager-webhook-hetzner
  namespace: kube-system
spec:
  repo: https://vadimkim.github.io/cert-manager-webhook-hetzner
  chart: cert-manager-webhook-hetzner
  version: 1.4.2
  targetNamespace: cert-manager
  valuesContent: |-
    # Group name for the webhook API (must match ClusterIssuer)
    groupName: acme.h3rmt.dev
    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager
    # Ensure CRDs are created
    createCRD: true