apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-echo
  annotations:
    external-dns.alpha.kubernetes.io/target: ovh-1.h3rmt.dev
    external-dns.alpha.kubernetes.io/hostname: echo.h3rmt.dev
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`echo.h3rmt.dev`)
    services:
    - name: http-echo
      port: 8080
  tls:
    certResolver: le
