apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        allowCrossNamespace: true
    gateway:
      listeners:
        web:
          namespacePolicy:
            from: All
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`test.h3rmt.dev`) && PathPrefix(`/`)
        entryPoints:
          - web
          - secure