apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
    gatewayAPI:
      enabled: true
    providers:
      kubernetesGateway:
        enabled: true
    # Legacy Traefik ACME removed - now using cert-manager
    # additionalArguments:
    #   - "--log.level=DEBUG"
