apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
      namespace: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
        namespace: home-assistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2026.7
          ports:
            - name: hass
              containerPort: 8123
          securityContext:
            # needed for networking
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          env:
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - name: config
              mountPath: /config
        - name: openthread-border-router
          image: ghcr.io/ownbee/hass-otbr-docker:7e60d50
          ports:
            - name: otbr-rest
              containerPort: 8081
            - name: otbr-web
              containerPort: 8085
          securityContext:
            # needed for /dev/ttyUSB0 access
            privileged: true
            # needed for networking
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          volumeMounts:
            - name: otbr-data
              mountPath: /data
          env:
            - name: DEVICE
              value: "/dev/ttyUSB0"
            - name: BACKBONE_IF
              value: "eth0"
            - name: OTBR_WEB_PORT
              value: "8085"
            - name: OTBR_WEB
              value: "1"
            - name: THREAD_BETA
              value: "0"
            - name: AUTOFLASH_FIRMWARE
              value: "0"
            - name: FLOW_CONTROL
              value: "0"
            - name: BAUDRATE
              value: "460800"
            - name: OTBR_LOG_LEVEL
              value: "info"
        - name: matter
          image: ghcr.io/matter-js/matterjs-server:1.2.4
          ports:
            - name: matter
              containerPort: 5580
          volumeMounts:
            - name: matter-data
              mountPath: /data
          env:
            - name: PRODUCTION_MODE
              value: "1"
            - name: PRIMARY_INTERFACE
              value: "eth0"
      nodeSelector:
        thread-usb: "1"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config
        - name: matter-data
          persistentVolumeClaim:
            claimName: matter-data
        - name: otbr-data
          persistentVolumeClaim:
            claimName: otbr-data