apiVersion: v1
kind: Service
metadata:
  name: home-assistant-svc
  namespace: home-assistant
spec:
  ports:
    - name: hass
      port: 8123
      targetPort: 8123
    - name: otbr-web
      port: 8085
      targetPort: 8085
    - name: matter
      port: 5580
      targetPort: 5580
