apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  type: ClusterIP
  selector:
    app: home-assistant
    namespace: home-assistant
  ports:
    - name: hass
      port: 8001
      targetPort: hass
    - name: otbr-web
      port: 8002
      targetPort: otbr-web
