apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  type: ClusterIP
  selector:
    app: home-assistant
    namespace: home-assistant
  ports:
    - name: hass
      targetPort: 8123
    - name: otbr-web
      targetPort: 8081

