apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authelia-install
  namespace: kube-system
spec:
  repo: https://charts.authelia.com
  chart: authelia
  version: 0.10.50
  targetNamespace: authelia
  valuesContent: |-
    nameOverride: authelia
    pod:
      kind: Deployment
      replicas: 1
      env:
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: authelia-storage-app
              key: username
    configMap:
      telemetry:
        metrics:
          enabled: true
      default_2fa_method: webauthn
      theme: dark
      webauthn:
        enable_passkey_login: true
      authentication_backend:
        password_reset:
          disable: true
        ldap: 
          enabled: true
          implementation: lldap
          address: 'ldap://lldap.authelia:3890'
          base_dn: 'DC=homelab,DC=home'
          user: 'UID=admin,OU=people,DC=homelab,DC=home'
          password: 
            secret_name: lldap
      password_policy:
        standard:
          enabled: true
      session:
        remember_me: "3 month"
        redis:
          enabled: true
          host: redis-sessions-master.authelia
          password: 
            secret_name: authelia-redis
        cookies:
          - domain: h3rmt.dev
            authelia_url: 'https://auth.h3rmt.dev'
      storage:
        postgres:
          enabled: true
          address: authelia-storage-rw.authelia:5432
          username: "{{ env "PG_USERNAME" }}"
          password: 
            secret_name: authelia-storage-app
      notifier:
        filesystem:
          enabled: true
    secret:
      existingSecret: authelia
      additionalSecrets:
        authelia-storage-app:
          path: ''
          items:
            - key: 'password'
              path: 'storage.postgres.password.txt'
        lldap:
          path: ''
          items:
            - key: 'lldap-ldap-user-pass'
              path: 'authentication.ldap.password.txt'
        authelia-redis:
          path: ''
          items:
            - key: 'password'
              path: 'session.redis.password.txt'