apiVersion: v1
kind: Namespace
metadata:
  name: authelia

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authelia-install
  namespace: kube-system
spec:
  repo: https://charts.authelia.com
  chart: authelia
  version: 0.10.50
  targetNamespace: authelia
  valuesContent: |-
    nameOverride: authelia
    pod:
      kind: Deployment
      replicas: 1
    configMap:
      telemetry:
        metrics:
          enabled: true
      default_2fa_method: webauthn
      theme: dark
      webauthn:
        enable_passkey_login: true
      authentication_backend:
        password_reset:
          disable: true
        ldap: 
          enabled: true
          implementation: lldap
          address: 'ldap://lldap.authelia:3890'
          base_dn: 'DC=homelab,DC=home'
          user: 'UID=authelia,OU=people,DC=homelab,DC=home'
      password_policy:
        standard:
          enabled: true
      session:
        remember_me: "3 month"
        redis:
          enabled: true
          host: redis-session-replication-master.authelia
        cookies:
          - domain: h3rmt.dev
            authelia_url: 'https://auth.h3rmt.dev'
      storage:
        postgres:
          enabled: true
          address: authelia-storage-rw.authelia:5432
      notifier:
        filesystem:
          enabled: true

