apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authelia-install
  namespace: kube-system
spec:
  repo: https://charts.authelia.com
  chart: authelia
  version: 0.10.50
  targetNamespace: authelia
  valuesContent: |-
    nameOverride: authelia
    pod:
      kind: Deployment
      replicas: 1
      env:
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: authelia-storage-app
              key: username
    configMap:
      telemetry:
        metrics:
          enabled: true
      default_2fa_method: webauthn
      theme: dark
      webauthn:
        enable_passkey_login: true
      authentication_backend:
        password_reset:
          disable: true
        ldap: 
          enabled: true
          implementation: lldap
          address: 'ldap://lldap.authelia:3890'
          base_dn: 'dc=h3rmt,dc=home'
          user: 'UID=admin,OU=people,dc=h3rmt,dc=home'
          password: 
            secret_name: lldap
      password_policy:
        standard:
          enabled: true
      session:
        remember_me: "3 month"
        redis:
          enabled: true
          host: redis-sessions-master.authelia
          password: 
            secret_name: authelia-redis
        cookies:
          - domain: h3rmt.dev
            authelia_url: 'https://auth.h3rmt.dev'
      storage:
        postgres:
          enabled: true
          address: authelia-storage-rw.authelia:5432
          username: '{{ env "PG_USERNAME" }}'
          password: 
            secret_name: authelia-storage-app
      notifier:
        filesystem:
          enabled: true
      identity_providers:
        oidc:
          authorization_policies:
            developers:
              default_policy: 'deny'
              rules:
                - policy: 'two_factor'
                  subject: 'group:developers'
          enabled: true
          jwks:
            - key:
                path: '/secrets/authelia-oidc-secrets/oidc.jwk.RS256.pem'
          clients:
            - client_id: 'coder-app-JQfSLMNSEf'
              client_name: 'Coder'
              client_secret:
                path: '/secrets/authelia-oidc-secrets/coder-oidc-client-secret.txt'
              redirect_uris: ["https://coder.h3rmt.dev/api/v2/users/oidc/callback"]
              authorization_policy: 'developers'
              pre_configured_consent_duration: "1 month"
    secret:
      existingSecret: authelia
      additionalSecrets:
        authelia-storage-app:
          path: ''
          items:
            - key: 'password'
              path: 'storage.postgres.password.txt'
        lldap:
          path: ''
          items:
            - key: 'lldap-ldap-user-pass'
              path: 'authentication.ldap.password.txt'
        authelia-redis:
          path: ''
          items:
            - key: 'password'
              path: 'session.redis.password.txt'
        authelia-oidc-secrets:
          path: ''
          items:
            - key: 'oidc.jwk.RS256.pem'
              path: 'oidc.jwk.RS256.pem'
            - key: 'coder-client-secret'
              path: 'coder-oidc-client-secret.txt'