apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: coder-install
  namespace: kube-system
spec:
  repo: https://evantage-ws.github.io/lldap-kubernetes/
  chart: lldap-chart
  version: 0.4.0
  targetNamespace: authelia
  valuesContent: |-
    env.TZ: "Europe/Berlin"
    persistence.storageClassName: "local-path"
    hpa.enabled: false
    ingress.enabled: false
    service.name: lldap-service
    service.type: ClusterIP

