apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ldap-install
  namespace: kube-system
spec:
  repo: https://evantage-ws.github.io/lldap-kubernetes/
  chart: lldap
  version: 0.4.0
  targetNamespace: authelia
  valuesContent: |-
    fullnameOverride: lldap
    env:
      TZ: "Europe/Berlin"
    persistence:
      storageClassName: "longhorn"
    service:
      name: lldap-service
      type: ClusterIP
    hpa:
      enabled: false
    ingress:
      enabled: false
    certmanager:
      enabled: false

