apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name:  redis-session-replication
  namespace: authelia
spec:
  clusterSize: 4
  kubernetesConfig:
    image: quay.io/opstree/redis:latest
  sentinel:
    size: 3
    image: quay.io/opstree/redis-sentinel:latest
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi
  serviceAccountName: redis-sessions