apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name:  redis-sessions
  namespace: authelia
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.4.2
    redisSecret:
      name: authelia-redis
      key: password
  sentinel:
    size: 3
    image: quay.io/opstree/redis-sentinel:v8.4.2
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi