apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn-install
  namespace: kube-system
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
  - wrangler.cattle.io/on-helm-chart-remove
  generation: 1
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: v1.11.1
  failurePolicy: abort
  targetNamespace: longhorn-system
  createNamespace: true