apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn-install
  namespace: kube-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: v1.11.1
  failurePolicy: abort
  targetNamespace: longhorn-system
  createNamespace: true
  valuesContent: |-
    defaultSettings:
      defaultDataPath: /mnt/tank-longhorn
      defaultDataLocality: "best-effort"
      defaultReplicaCount: 3
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 3
      defaultDataLocality: "best-effort"