apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager-webhook-hetzner
  namespace: kube-system
spec:
  repo: https://charts.hetzner.cloud
  chart: cert-manager-webhook-hetzner
  targetNamespace: cert-manager
  valuesContent: |-
    groupName: acme.h3rmt.dev
