apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn-install
  namespace: kube-system
spec:
  chart: oci://ghcr.io/coder/chart/coder
  version: 2.30.0
  createNamespace: true
  targetNamespace: coder
  valuesContent: |-
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-cluster-app
              key: uri

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-cluster
  namespace: coder
spec:
  instances: 2
  storage:
    storageClass: local-path
    size: 3Gi

