apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: coder-install
  namespace: kube-system
spec:
  chart: oci://ghcr.io/coder/chart/coder
  version: 2.30.0
  targetNamespace: coder
  valuesContent: |-
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-cluster-app
              key: uri
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: "false"
        - name: CODER_ACCESS_URL
          value: "https://coder.h3rmt.dev"
        - name: CODER_OIDC_ISSUER_URL
          value: "https://auth.h3rmt.dev"
        - name: CODER_OIDC_CLIENT_ID
          value: "coder-app-JQfSLMNSEf"
        - name: CODER_OIDC_EMAIL_DOMAIN
          value: "h3rmt.dev"
        - name: CODER_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-oidc-secret
              key: client-secret
      service:
        type: ClusterIP

