apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: kube-system
spec:
  repo: https://juicedata.github.io/charts/
  chart: juicefs
  targetNamespace: juicefs
  valuesContent: |-
    metrics:
      enabled: true
    dashboard:
      httpRoute:
        enabled: true
        parentRefs:
          - name: traefik-gateway
            namespace: default
            sectionName: websecure
            kind: Gateway
        hostnames:
          - juice.infra.h3rmt.dev