apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: juicefs
  namespace: kube-system
spec:
  repo: https://juicedata.github.io/charts/
  chart: juicefs-csi-driver
  targetNamespace: juicefs
  valuesContent: |-
    metrics:
      enabled: true
    dashboard:
      httpRoute:
        enabled: false