apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name:  redis-juicefs
  namespace: juicefs
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.6.1
    redisSecret:
      name: juicefs-redis
      key: password
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi