apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nvidia-gpu-operator
  namespace: flux-system
spec:
  interval: 12h
  url: oci://nvcr.io/nvidia/cloud-native-charts/gpu-operator
  ref:
    tag: v26.7.0
    digest: sha256:23268170f1b608365ef8c15e0c0df87bff0017768e048bd9e73e41a1096299e4

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: operators
spec:
  interval: 2m
  chartRef:
    kind: OCIRepository
    name: nvidia-gpu-operator
    namespace: flux-system