apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nvidia-gpu-operator
  namespace: flux-system
spec:
  interval: 12h
  url: oci://nvcr.io/nvidia/cloud-native-charts/gpu-operator
  ref:
    tag: v26.7.1

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: operators
spec:
  interval: 2m
  chartRef:
    kind: OCIRepository
    name: nvidia-gpu-operator
    namespace: flux-system