apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 12h
  url: oci://quay.io/jetstack/charts/cert-manager
  ref:
    tag: v1.20.0

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 2m
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: flux-system
  values:
    installCRDs: true
    replicaCount: 1
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-hetzner
  namespace: flux-system
spec:
  interval: 12h
  url: https://charts.hetzner.cloud

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-hetzner
  namespace: cert-manager
spec:
  interval: 2m
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager-hetzner
        namespace: flux-system
      interval: 1h
  values:
    groupName: acme.h3rmt.dev