apiVersion: v1
kind: Secret
metadata:
    name: hetzner-dns-credentials
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:xm57BHhWbs6fx+o6Y4+91IMoxi8RAIfTlW/4B3Jy79OYJginr/zv75hw+OsaGn9E7WrRVI2OZ9jKbgdlGKI3WA==,iv:dQRt4DpVEiUrPq5Q/T3mRXhOdanjj6MFtPufLHjFkFE=,tag:fm6bZuEolqLxcVHHMvEdIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QzhTQ1dmUC9vSE02cVZi
            Y3Zwcm1aN3QzRVJ1enMxdGRUbnJiTE5iUGcwCmNDWjBsckR2SU15ZUN4cGR3cDhy
            c0ZINlhxZVNjVVZQR1E2T0NVK1ZXclEKLS0tIDRqT3VabHl6bVd4djNaWU9WTlpZ
            MUgvWkxkQXUxR0FRVmdvcDgwejNrTGMKiIG637MCm+aCwEONhS04wIIMDS03eVhD
            BhAvnLFoYxN/+kewtlXpCbvtzygx7C8IFgetxGKE0mFalFbJdGPQJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T23:34:14Z"
    mac: ENC[AES256_GCM,data:Lv3kOHJ0b8g00vEEP+UTVoLD96ZM/4WIqw6485y3VCFn5PrxrCjq/nZOtqW7Unyl60z4ZVxeu69m6mtOo8xNiH3KnrTrzpMYQ5APsw+UZU2PrWQFcg1KZFdq/iL/F2ad1/0E1S+ZolkbhojF5z6fMFy3fyuyNf7CzvzjEqIQRQU=,iv:3vcaWa1EHslCTOCMjt5/rbadzKkZdW6X+NcEVK+Y54U=,tag:qLj2NrSVOD0vAkHAbIoMhQ==,type:str]
    version: 3.13.2
