apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
        - name: piper
          image: lscr.io/linuxserver/piper:latest
          ports:
            - name: wyoming
              containerPort: 10200
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Berlin
            - name: PIPER_VOICE
              value: de_DE-thorsten-high
            - name: PIPER_LENGTH
              value: "1.0"
            - name: PIPER_NOISE
              value: "0.667"
            - name: PIPER_NOISEW
              value: "0.333"
            - name: PIPER_SPEAKER
              value: "0"
            - name: NO_STREAMING
              value: ""
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: piper-data
