apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
        - name: piper
          image: rhasspy/wyoming-piper:2.5.2
          args:
            - --uri
            - tcp://0.0.0.0:10200
            - --voice
            - de_DE-thorsten-high
            - --data-dir
            - /data
            - --download-dir
            - /data
          ports:
            - name: wyoming
              containerPort: 10200
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: piper-data
