apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      nodeSelector:
        location: "home"
      containers:
        - name: piper
          image: lscr.io/linuxserver/piper:latest
          ports:
            - name: wyoming
              containerPort: 10200
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Berlin
            - name: PIPER_VOICE
              value: de_DE-thorsten-medium
            - name: PIPER_LENGTH
              value: "0.9"
            - name: PIPER_NOISE
              value: "0.667"
            - name: PIPER_NOISEW
              value: "0.333"
            - name: PIPER_SPEAKER
              value: "0"
          volumeMounts:
            - name: data
              mountPath: /config
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: piper-data
