apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openebs
  namespace: kube-system
spec:
  repo: https://openebs.github.io/openebs
  chart: openebs
  version: v4.4.0
  targetNamespace: openebs
  valuesContent: |-
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    loki:
      enabled: false
    alloy:
      enabled: false
