apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openebs-monitoring
  namespace: kube-system
spec:
  repo: https://openebs.github.io/monitoring/
  chart: monitoring
  version: v4.1.0
  targetNamespace: openebs
  valuesContent: |-
    kube-prometheus-stack:
      install: false
    localpv-provisioner:
      enabled: false
