apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: filepool-ovh-1
  namespace: openebs
spec:
  node: ovh-1
  # 2 TB disk image created with `truncate -s 2T /mnt/mayastor.img`
  # Mounted as loop device with `losetup /dev/loop1 /mnt/mayastor.img` (as systemd service)
  disks: ["uring:///dev/loop1"]

---

apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: filepool-hetzner-1
  namespace: openebs
spec:
  node: hetzner-1
  # 30GB disk image created with `truncate -s 30G /mnt/mayastor.img`
  # Mounted as loop device with `losetup /dev/loop1 /mnt/mayastor.img` (as systemd service)
  disks: ["uring:///dev/loop1"]

---

apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: filepool-home-2
  namespace: openebs
spec:
  node: home-2
  # 2T zfs block device created with `zfs create -V 2T tank/mayastor`
  disks: ["uring:///dev/zvol/tank/mayastor"]