apiVersion: v1
kind: Service
metadata:
  name: music-assistant-svc
  namespace: home-assistant
spec:
  type: ClusterIP
  selector:
    app: music-assistant
  ports:
    - name: http
      port: 8095
      protocol: TCP
      targetPort: 8095