apiVersion: v1
kind: Secret
metadata:
    name: hetzner-dns-credentials
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:JZmp1z+l9mVidjMxO+oDwI3ZJ0ckeewWQNjei4dYw5N+pNpWyAUgbTbYljNPEAwNwmchEoD6Gm5iNXJmjiHXUQ==,iv:SKojDgvnKWw1+sLmzics85L3fNpzoXwJNiV3tqR7zRU=,tag:ehsVki6zbF4NZsv1DpoQzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYktTM29uQjJWMnpzYmtS
            MkQxUHp2VnFtajkzN04xK3FxcjEwR2M2L3pRCnN1eGtuVzJPQS9CSWpLZ2kwQUgx
            WWI0RmE0bjBKcHBwTThKMTZsVWphUkEKLS0tIFJqSmVpdnZoVnFLekp2L1ZyTkFB
            NzRiVzRXdDUxYXFFblh5dTNBL2FiODAKn7j5nZQ97rrJVsyzYJlFcfGgRULBPLJV
            WrlSOzcF5QjbQxdRnVim/aJRx2bDNmbbGQUxMnEarQqEZmG01/7jpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T21:35:46Z"
    mac: ENC[AES256_GCM,data:oNsiwwQ9nFU3RSFJHonRIL8r4FOoRAi4/kmVb+LCHRWvBXOX6IN6beuJgyoW8l7eew8blvzkqXcB3WKEICD0oDqF8MIEpOG8lRZfzg2q42WuZIbfOWNRyuBVnahLdjyE0T7vJ2b5oEDX+d/R9B3a5K1VRWlCLhR6kqfqbk450bk=,iv:YWLVnEZ2ITYQ4E5GTK3o7cH/kx4mYIYuS7HfOcStdMg=,tag:lvmSPNN48ZUng3KFHMzgaQ==,type:str]
    version: 3.13.2
