apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: headlamp-values.yaml
    namespace: headlamp
    files:
      - values.yaml=headlamp-values.yaml
