apiVersion: v1
kind: Secret
metadata:
    name: garage-secret
    namespace: garage
type: Opaque
stringData:
    adminToken: ENC[AES256_GCM,data:dc3/0v2JYk3enEokGUTsmMVfbpJYpm1diIAgU4o+r9MTAaEsn6NB7CnK02s=,iv:4HJXEU4VjhPZ5lR3Ekgd6cPwM8rd0/o8tTvAJ0HlAWk=,tag:k+W7qQHT+SmmxbHiTOwX+A==,type:str]
    rpcSecret: ENC[AES256_GCM,data:icLpCgoJD5V6mPbmGtI1Ao16uWGTpF7Mg2ti5ylQjnCcGXayHpUj3wa1H7TuIzMuA2UQUOaKdOktoWlUihz8gQ==,iv:fkIH1KBSsfg3SLL6VkS33D20vcc8K3u6TH2ogHedLBo=,tag:FBSQzsx7ujXf+GBnaaWihw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWnc5ZG1JWlh5dWtHaGJE
            ODJZSzAwaDhVQUZrT0t6UWVIaWRMd1RLa1NzCnRPeVp6ZkNlMnl1QzBtbjRES3lz
            WnVuNDVIRmJGTnNjUWt4dDI0QjUyVlEKLS0tIERmNUJvcmxFK04veE5WSU9vZ280
            Mjl5Rm5SQWhJYnpkQTNnaUtTMjY2ODAKuGvzqOZyKlMIN062dSVENreCMOOIaSvo
            8qn7siebbJmwO4lHSAPS1QyL2olwtPJAKqE7bUo2TY1w3t5eXd9IuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T19:23:32Z"
    mac: ENC[AES256_GCM,data:wJbqokYxhWNOjGGETX8L4BGZKDabel0TJ11U196wj38/dVr94bNmKfWibte7rMtj/+6psniDl4JOvIA7SpDqlXpFOHWOMOrR3QRzaBNXu/MurzQwV1RDaVhK2wusXbTiSj2+zgaIov0DDlymoimM0BMafuSi7OSJtExicHGSN/0=,iv:ryR97ug00ifdHCGTHWRrXRJNZM1Na6ILXpPuiH1sq3U=,tag:Nos0JPvXajxoOLwEqeVjhg==,type:str]
    version: 3.13.2
