apiVersion: v1
kind: Secret
metadata:
    name: juice-1-s3-secret
    namespace: garage
type: Opaque
stringData:
    key-id: ENC[AES256_GCM,data:uEry2mffLX3pLe8ezHlVrTpBAzOFgwt23vc=,iv:UNqteNuuM+yt3Zx5vUVZS6b2ANXIaHDiA4nLQn5ML5c=,tag:aPvY+zkjUXIrry4Sr/o96A==,type:str]
    secret: ENC[AES256_GCM,data:RzJDJwoBrUfApxVg0y5sB4uZx0mWNHkZH0YE3SpEawRMJFnYGc/LhqHpjnBzapQmWPAeuDfvE9QT3WVJU1X4Cg==,iv:zYlHBhj6l59E7DLpdurgDgija4xUQ76ZYbdB7w4JPJY=,tag:LdF5qZUnw3xeiIwJU3y7hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT1FGeUkxRHdSN3JLaWlZ
            Q0oyZEJzVDhTL2phOUtOdThOSHArZ2tHV2lNClFTWmMveVgyeWlHMThNTGdCQktD
            YnJBVStod0ZiMyswN0lTTkRya3E3bWcKLS0tIGczOVdOMmJzNVJnQW9QWXRqYTh6
            d2F0R0t6S0dYNUFjZGVGQ2F6azVOcXMKrOMCQwDLJK/Ja0fXVj04PBsEA4OFw1nZ
            8yz/c0xBdcsZ6WGCrWwKCAIOdmDs95hi1SMj7YkG0N4rriXwqC/lGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T19:23:29Z"
    mac: ENC[AES256_GCM,data:L9yHUMFBzOgAPelbDsBxFGkiaEGbHCYuBgvN8jbJc8jHz1EDtF11LvZKm0Of8bEDVwXMFgoA1vZNXGFJCSroXu+KdbdvL1kLOvCqv2Wtk3xt18FDH5VH+TigmjPbCyq6weDLV4KZl5r5GbwpjwNVQANFNYMzLheoaqTkCWwVLUI=,iv:qDStFxeb3A+pDkZbM85XCZBOylXUzOw3C1YnUQYRyoc=,tag:4huRL7Ic/jL6FXa7mAu6ng==,type:str]
    version: 3.13.2
