apiVersion: v1
kind: Secret
metadata:
    name: hetzner-dns-credentials-external-dns
    namespace: kube-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:l+PLeVuczGjK9bIIfvjAJEvERGRLg9aA4bkXWwNXs4jMmrZO95IY/4VsrEdVAj+MTKcoUUf7d786sJC8ma4lvQ==,iv:4lrj3S1jpVSovxeEYVCCrbCv1KAn3/kfu2giGTvjKBw=,tag:4i+AfiLHZ5TGV8/4+DRSgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWDBoVXRvZDF4b25QejRL
            aEUzU2pEckpkbEtKd1ZsT1NuallOREFPejNnCktQbXc5M1dBeXBoYzdUYVFEQUtD
            ZHJkUHl1UXkwMFM3VmMwVGFPSzNFbUkKLS0tIG5EaVBMSnY1cG5EeVJnRmhKMkEz
            UE1kelg4Z1JmM1p4RFhUVWJSWGlEazAKQoXW/2vjPjwR9esADMnAlaOasPqQCMBA
            JvwNPt9EQPRQMpg0zf23FBJqkYqxltdzPeBNDkFuki6Ve0/kubnCOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T23:33:35Z"
    mac: ENC[AES256_GCM,data:b+DungGTXGLUzv8vEM8ZFOGpts0H89G/1oXSlmkkpEihZIEGtQyCo4lT7BUe3PN5rExJXHvgHjXCi9N+Es3loiIDgjw9s0db/+RXP3nscYMmxbY2uOBrLYCiq/sO/7Zv4mFfX36sZD7kQaRUy8DRd3u9yF6AePVwFRSAUvVx41A=,iv:0P+oZml4keLEPvnzqQu5OHLMIopu7cVzArX9DZX+A5g=,tag:aMqLk+GY39oVpsagHnbMSQ==,type:str]
    version: 3.13.2
