apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prom-datasource
  namespace: monitor
  labels:
    # default value for: sidecar.datasources.label
    grafana_datasource: "true"
data:
  prom.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitor.svc.cluster.local:9090
        jsonData:
          manageAlerts: true
          timeInterval: "30s"
        editable: false
