apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: garage-monitor
  labels:
    name: garage-monitor
    release: prometheus
  namespace: monitor
spec:
  namespaceSelector:
    matchNames:
      - garage
  selector:
    matchLabels:
      name: garage
  endpoints:
    - targetPort: 3903
      path: '/metrics'
      scheme: 'http'
      interval: '30s'