apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana-operator
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: grafana-operator
  version: 5.22.2
  targetNamespace: grafana-operator
  createNamespace: true
  # Install the grafana.integreatly.org CRDs.
  valuesContent: |-
    crds:
      immutable: true
