apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
spec:
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  config:
    log:
      mode: "console"
  # Default secret with admin credentials is disabled as the username and password are supplied externally
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: credentials
              readinessProbe:
                failureThreshold: 3
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
      strategy:
        type: Recreate
  httpRoute:
    spec:
      hostnames:
        - monitor.infra.h3rmt.dev
      parentRefs:
        - name: traefik-gateway
          namespace: default
          sectionName: websecure
          kind: Gateway
      annotations:
        external-dns.alpha.kubernetes.io/ttl: "300"
