apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-operator-crds
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus-operator-crds
  version: 27.0.1
  targetNamespace: kube-system

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitor
  valuesContent: |-
    namespaceOverride: monitor
    alertmanager:
      enabled: true
      route:
        main:
          enabled: true
          hostnames:
            - alerts.infra.h3rmt.dev
          parentRefs:
            - name: traefik-gateway
              namespace: default
              sectionName: websecure
              kind: Gateway
          annotations:
            external-dns.alpha.kubernetes.io/ttl: "300"
          filters:
            - type: ExtensionRef
              extensionRef:
                group: traefik.io
                kind: Middleware
                name: middleware-auth-alerts
      alertmanagerSpec:
        replicas: 1
        storage: 
          volumeClaimTemplate:
            spec:
              storageClassName: mayastor-2
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
    grafana:
      enabled: true
      defaultDashboardsTimezone: "Europe/Berlin"
      admin:
        existingSecret: credentials
        userKey: GF_SECURITY_ADMIN_USER
        passwordKey: GF_SECURITY_ADMIN_PASSWORD
      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        storageClassName: mayastor-2
      operator:
        dashboardsConfigMapRefEnabled: true
        matchLabels:
          app: grafana
          category: dashboard
    nodeExporter:
      enabled: true
    prometheusOperator:
      enabled: true
      fullnameOverride: prometheus-operator
    prometheus:
      enabled: true
      route:
        main:
          enabled: true
          hostnames:
            - prometheus.infra.h3rmt.dev
          parentRefs:
            - name: traefik-gateway
              namespace: default
              sectionName: websecure
              kind: Gateway
          annotations:
            external-dns.alpha.kubernetes.io/ttl: "300"
          filters:
            - type: ExtensionRef
              extensionRef:
                group: traefik.io
                kind: Middleware
                name: middleware-auth-prom
      prometheusSpec:
        podAntiAffinity: "hard"
        retentionSize: 30GiB
        replicas: 1
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec: 
          volumeClaimTemplate:
            spec:
              storageClassName: mayastor-2
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 32Gi
        additionalScrapeConfigs:
          - job_name: 'wireguard'
            static_configs:
              - targets:
                  - '10.0.0.11:9586'
                  - '10.0.0.51:9586'
                  - '10.0.0.102:9586'
    thanosRuler:
      enabled: false
    kubeStateMetrics:
      enabled: true
