apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: kube-system
spec:
  chart: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack  
  version: 82.15.1
  targetNamespace: monitor
  valuesContent: |-
    namespaceOverride: monitor
    alertmanager:
      enabled: true
      route:
        main:
          enabled: true
          hostnames:
            - monitor.infra.h3rmt.dev
          parentRefs:
            - name: traefik-gateway
              namespace: default
              sectionName: websecure
              kind: Gateway
          annotations:
            external-dns.alpha.kubernetes.io/ttl: "300"
    grafana:
      enabled: true
      defaultDashboardsTimezone: "Europe/Berlin"
      operator:
        dashboardsConfigMapRefEnabled: true
        matchLabels: 
          dashboards: "grafana"
    nodeExporter:
      enabled: true
    prometheusOperator:
      enabled: true
    prometheus:
      enabled: false