apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
configMapGenerator:
  - name: pocket-id-operator-values
    namespace: pocket-id
    files:
      - values.yaml=pocket-id-operator-values.yaml
