apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pocket-id-operator
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/aclerici38/charts/pocket-id-operator
  ref:
    tag: 0.15.0
    digest: sha256:79493ae0d7c1d1be8788eef74d4c61cc9c744fcbe6c6e60c35ac81f21288ffca

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
  namespace: pocket-id
spec:
  interval: 2m
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: pocket-id-operator-values
