apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    semver: "41.0.2"

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: flux-system
  values:
    deployment:
      replicas: 3
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    ingressClass:
      enabled: false

    gateway:
      name: traefik
      defaultScope: "All"
      annotations: 
        # external-dns.alpha.kubernetes.io/access: "public"
        # external-dns.alpha.kubernetes.io/hostname: "k3s.h3rmt.dev"
      listeners:
        http:
          port: 8000
          protocol: HTTP
          namespacePolicy: 
            from: All
        https:
          port: 8443
          protocol: HTTPS
          namespacePolicy: 
            from: All
          mode: Terminate
          certificateRefs: 
            - namespace: kube-system
              name: wildcard-h3rmt-dev-tls

    # Privacy-friendly Prometheus metrics (cluster-internal only)
    metrics:
      prometheus:
        # disable if deployed before prometheus
        enabled: false
        addRoutersLabels: true
        service:
          enabled: true
        # disable if deployed before prometheus
        serviceMonitor:
          enabled: false
      addInternals: false

    providers:
      kubernetesGateway:
        enabled: true
        experimentalChannel: true
      kubernetesIngress:
        enabled: false
    
    ports:
      web:
        http: 
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
        observability:
          accessLogs: false
          metrics: false
          tracing: false
      websecure:
        asDefault: true
        http:
          middlewares:
            - default-auth@kubernetescrd
            - default-strip@kubernetescrd
        http3:
          enabled: true
          advertisedPort: 433