apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      nodeSelector:
        thread-usb: "1"
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.1.2-alpine
          command:
            - /bin/sh
            - -ec
            - |
              chown mosquitto:mosquitto -R /mosquitto
              chmod 400 -R /mosquitto
              exec /docker-entrypoint.sh /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
          ports:
            - containerPort: 8883
              protocol: TCP
              name: mqtt-secure
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
              readOnly: true
            - name: auth
              mountPath: /mosquitto/auth
              readOnly: true
            - name: certs
              mountPath: /mosquitto/certs/
              readOnly: true
            - name: data
              mountPath: /mosquitto/data/
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
            defaultMode: 0440
        - name: auth
          secret:
            secretName: mosquitto-auth
            defaultMode: 0440
        - name: certs
          secret:
            secretName: mqtts-tls
            defaultMode: 0440
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data-pvc
