apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - secret.enc.yaml
  - cert.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
generatorOptions:
  disableNameSuffixHash: false
configMapGenerator:
  - name: mosquitto-config
    namespace: home-assistant
    files:
      - mosq.conf=config/mosq.conf
      - acls=config/acls
