apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-pvc
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-longhorn
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
