apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-longhorn
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
