apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: mqtt
  namespace: home-assistant
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  parentRefs:
    - name: traefik
      namespace: kube-system
      kind: Gateway
      sectionName: secure-mqtt
  hostnames:
    - home-mqtt.h3rmt.dev
  rules:
    - backendRefs:
        - name: mosquitto-service
          namespace: home-assistant
          port: 1883
