apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-auth
    namespace: home-assistant
stringData:
    pwfile: ENC[AES256_GCM,data:Ax3rnED5BrEuUGUeFdAbn/ffLXiQhMc0cvHJiDb6fwkNsfHNHsEkaPAMrqsBy1JuNaBDOOB9iF5QEbIKZ+zptEuJH08eHSsLkrdSaJXY54oM7D7KGBg/pUMwydpRrhdretqSXduyRK11hp1BEGbknwN0bbadfu4DvlrFqHtts6FYQ297fEdVSR+dHkmkzHAaXAsoFIB1Y3TXuFfx4wBOOMU0igfCS1ypnrMn/x760Bi8v2/A1esnPKc2MLhE0hDVJMRQ2afgC27YF8bIJ/0/R6SWJ3LVD5TcK5biMaMKBRMZdy5witTQxM1KFgERxQSl2b2F0aNjO17ZCVWGEgQndIekgsRgJn+ruHdzKhQJgdP20BX1UdA9xEXu+olHytasPIgGcyBhZqo1uUNPsafh1tnKarnx3w67bmxk8mFn9iCV6HVE2qyU0AV9za6y6aMXcM2m0lnOg9m5mVg7tLg2p6pDuc9ZycbthnlIdEF3lCT1S0AWZwhHpNXIO/fNNGqzEWl1TQvyJdo+6LB/Mt3Xr6EAWUIdowpcvbcBnVK+nGYnUgxYWu4BfmsQyF3B6Js9bewrxSWMfIiKdiKhTFaTKp8Zz4K/6BLT0ZNPLEcVa4pf/k8VFC24Pqt6Q2DTpx00Yec5EF/pjWy5k2TnbzbTBtQLmoslHph8A5fyqeTQ6gB/aCMj5cOY5XNvnJsQ87fSweQb/RatIbxpUV7E6oPtGuLH6sqqOduWBiOCgEHR97es5++9nA6g+CA/hn+2afcF5OVuttrjyCjFuNDhLasfhP+Zyb/375avh6vlEar1agTx45l09UeTnpbxLhT2w3CbW4ldbQ6wmxwrBUST05qAux4XPT9nN8tLQ7bdWNG53vkzDKbb/0nSvGMSghvFLrHNbsuFTlk2QZirmkIKcNosqd6Qs19EX722vjmvDZV57G0x0eg1Ma3h5ocQD3v550CCkFdxUuL/pvMnShA4rywziqrcwNjVoDmggJ4gYYrHmBe+cjz6BwRRFJUb2lt5CTabe5+bKHi6SEZ+lovxip15RIl1+l6vE5EL,iv:7FqXDx42ex7m+2vqQWrjIM5mwI16IDSQW/CqMjJ9HHc=,tag:TzYnqz170ZzvM8rqICdvXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRmE1aE5mb2NmSmM4eXB4
            ZzJvOHlzZ2dESTY0bmpBMDV0bkhNNENWVEQ0CkxtN0t6ZzdPOHhWNEViM0Q1dzZV
            WjZFamhpdjhyeEpXeTRicWVaWjJocHMKLS0tIEtaczVoNFFzbkwxQ05nVHExanN2
            ZUYyREkycVhTNTN1SWJPUUdSbmJQQ0UK7unFAOoBkvrJS87F/xX/BWZA/2yyHNVP
            N/LcAXThU5EkcA+zeo/dhfa5I169K3vnUn3Mig2uKVr/N5oiqRheOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T20:18:26Z"
    mac: ENC[AES256_GCM,data:QoThRMVZKbGKU+IrJHsF0ti1xKaWnUQ5c939id2HWZA36anIvQHN6M2hTh1I5LBDhJ3oO2LISQHPhvxK0iI13crkaT4grV/fb5nhi2h/GPpwuzoTkVRHB5JhWyXcShzOyr1V6/EwkDUVlQO7KHKPl+wW60TInUv3t1qEO4QxazI=,iv:V5VoVeu+hU34jShi2f6LR5cfI2rO/Rx6tIl87OucN0c=,tag:ziRLrHKz0WxFfjV6ybAhQA==,type:str]
    version: 3.13.3
