apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-auth
    namespace: home-assistant
stringData:
    pwfile: ENC[AES256_GCM,data:PSkk1g3GD8JfiVa53CgT5nrsyLHMJ199rgYLhfesNk6AJVeC1E+/vD1DFI9M2hV+fyT6VCUTnyDp2hDJ7XPkJI2mFvyY5GA5wJoltleGMBZSxxfOMW1DlQRhkj6EqM+LOyhrODv1MGa3lR00QuCZNteIreLBXUtlUMI0KTN341gciE5SZoZx5HsbdxE3GrodvmYFx0m76o6fqXTgeBcyiufq5U3Zwyz7G35VwBYMWfBV5qZxGYMCa9vPVpk7Q0/bmunNnTWqvlYYLBOJ1V0PqcVE13dPzGHTJwHJGcZvLKl7VaeY3NdhDO1A01l1LcjF4K5pie2cRrfGrM7SKwGCs338f4wvoCW2IGFheA4blRlN2bl2X4b5aBT+Uv0MaCWZ8kGBxqAZzJeHG1roaP2wSOcUteAH18YWrUNQIs0eRqqrpSEehbnYAAnfQGcGIKeWiNDy14HR0fq4oOnZAtHLdyFbJa+pAHbJPEPeLy9CVQgJ8WCvQbHFdkX8h+9Y+Y2aNu1z+O7Pn7mrCRgG/KUKElSwOgvsfSCszYjgMV6IRztKMXhtaAO/FfZkUpy1VjLN8yZFaqIxiP+upjkU8MAwiS2Oxo/qAEssXG9S4pQN2lnr7PskZIJI0qPT8TND45BFkQP5WGZG8bi3taE9YNf+SaFibjkKdIjX7f3OonFZ7GKQbPtzuxYc9v3Zxasi6dLzpnAiR6b++Rlwg4c7sDmZ4UEG53VAEgDq77uborbkT/8HlwccFprZAVvMtidlxfRZ86YvmWan/CopuFbwu6Yx8i0plwmmSpMqaWNk8uo737K7g1d6m7/lSZmTEzopOFE/qPc6Y99x3a1KJTDFiJYBJn+YuDQ+0flTvBeXKQm54N0IygX3DAgQmkT5L9F/Oua7zJ09rkSqI5ofcsbidhEywMHnME5uQeyJNJwmH0ezvku1JRPXoWySFDKBCQ00L0p/N0ToSu4XRbsUqYfNubfjW1TQT5U97J8T6hg3EH9aOTvvUMmebW4/zn2SzAF65e3OmGNhJPZWC3aL1tIyz158gdUTySxDldrD,iv:3/7Gx74l0YnPDgp1NE0I0FDxKnAdNB6Ky//AcyAyFQo=,tag:pY5J1VdsXI2F9j3zQS0jJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQVBRcmlKQkNyRHY1M2ZS
            blUxSWRHNTRzK0xyckw3elNNYkpUTjIzRTJBClM1WmwyaUR6UmorMkRuUWh5ZzBE
            eXJuNUVFQzlGeU0xbVpvTjcyMjg1dDAKLS0tIHRlbEV5TlZ6MnpibksrbGFEZ211
            UElJelU2bnJKcEJVU1JLSFh3Q25SMXcK1guVMldzSqBCS5tTJnN3u0BiCH0+5bij
            49N2QdaB+YOSxUbFPTT6mq+phvGkMrru9G+j3viJVRmDbFNedjv0bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T10:25:10Z"
    mac: ENC[AES256_GCM,data:2KaLcABngVmzR1y0hEtqXtCTlmUyXR7S8hemcdmPnVuOVquK5rV12qjHwMQh1ckhtDgveQF0Y4i7NTmCD3U/ttNFR4wgRvzmW7S0qTFquU5QheO5HKFj9k8ZIk4q0JIUJcWtdh48Bp+F668hukxCzho1kcPN9JNRoMtOS5IOuug=,iv:ZW56kfggUiyM3qAr4AIfdecfUhhsERXnSgThBr4K0nI=,tag:Uxpiqn7R+XboA0P8JB19lw==,type:str]
    version: 3.13.3
