apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-auth
    namespace: home-assistant
stringData:
    pwfile: ENC[AES256_GCM,data:cFOBscigJY/V3cWAVyXQmx5dN6qzGNywv+cBbctMA3VHkSe2AN+R24IETTbK9rNK5kkfAtFkc+DoY1KnZ00Bph9ZEYciTnyaLM/n3Wg4fu2sTpZI7JqYxShb78WQhJI+Ssm/vy0sYsz7tZm6b63E8HodnNAmzOtUtX1HFQliQao6JNlIi310YzNbQkLgT9sOdJXRv7O14b9DT2N++8buqzV3h1u8vZFO49XAIGk/BCw1RENMqzvxL5TJv7TWLzpu9jSPK0zIeHC8ua6FwrVZOEOZVAXW3FYDGK/OAD4lub0CQ5N0MIfLvh3G5sMwzNEA5lKclVUXK8gxyw3Aa8pkIEvC5gr2oqpbTaxC0h/SCG7KpJZ1fjoefcrv7sC4BmdvWc52X1YIWzZiH7hSWG0KuufeNaWYJyEWWpcXJKuL0F9eNgph5/QKBYS6xGxtS4wZuEbYnnYKw/oIBUsTD5++0XvmrC/Tn/dPKWkagDotWoWHDG5sXEQ2AcFPh8pN5y9NS5kxrDP9kZEB17wDtWowW5WWkdzQvitRDro7WrIwvXYiQe/K3mMZ/Pf57FUOpZZ6QNFVanzLhUtnyld9I9o1z9TD05/eTYv6b/B/54ZDjKpYlj7znE2wTA5D8bq8KOG05f+F0nEdGmXZn0Xx2oRKiyY5JtKo468yCZR6t8nwi3CUQK0O+SjasHEM8CDNWpUGq2HCKsSS3O38h8vHJSVIdhYvwh8Tx+l5DmfieMD41fw0ctsRcz1y7AM4/xSvjXPNiXG0ueoOobaHetQMlYcDvRoBC0NKWVEfOofADZIeiCVCxPirzqaWSNgZP2Rsusvsg+6fiteeFx6IwG0FNbPL0FUhA1DEz7Pg4QjSddNMnJTQ6ek2/1OoSBNngPRtL1T6sME0UwEtaLapKkuCMBLgCbn3F1JwePmA0GsOhdE7hPU5y6mvznAu7HPzOnvJmsAv3bjR8VFkFy5adkLZdd29XI5zo18c9Tgx0jIjLkbL,iv://ppUuAT8ShWuq1JyoRg9tRUCMC4zPxnGYfxtNCbK3E=,tag:uLkfZ3cSKiScQhkZYJHckw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQUc3N2hkYnk1aXpleGVk
            VXUveUtKeW5adGJiYnREZHJ0cVN6WFhZeG1VCmhIRFJkQXg4OEpMMTB1ZG9jZGZZ
            NTU4ejhValRmY2VkMEU2cjU5WG9iRFEKLS0tIDR0ekhZbVRCZFd0V1gzRS9wYUto
            K01CNE1KRytjUjdIY2p5V1o5ZGdtMG8KHp1jSVfwzu2vcSBm35jw0hH5+R0TVenn
            LTqXb91NVIJGuA3yUJ/GcUqIGaWJQISFEnsZ6n5nHSp43z9KDf6E5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1agyztcavhvlahvm0tau5xfzzje66cygw6czvtheysmjacx4updtqgcl8q9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T23:15:14Z"
    mac: ENC[AES256_GCM,data:wV6NymI6ZmyzJvuonSwDHc9YOscpOBRHjOpvc4T+O8yQ1YHASldMtni9sLxzPiJrzrWeTewP0WzR1exfMf8WVAoykQ30HjqLoXUxAxCi6ydbW90lrYliOnQYlM43+6wXZNQEpyGgpyhu56dbETKAGubEqzAL7TLTdb2w2umiE5Y=,iv:IDNta6lzoSyafHN8IhUZWERzWlGKRcEVwOjwLJ0ukl4=,tag:hLMfPyKSyKZ8InDM0f6EfQ==,type:str]
    version: 3.13.3
